### ISSUE TITLE
Unable to load "messages", getting 401

### ISSUE THREAD

**Issue by alvarocamina** [okta/samples-java-spring#107]
Hi,
I am trying to get the essentials of OIDC flows and ended up here, setting "samples-js-angular/custom-login" (https://github.com/okta/samples-js-angular) as Front-end and this "samples-java-spring/resources-server" as Back-end.
I managed to run the FE app (Angular) on localhost:8080 and I can see ID Token claims on "Profile" tab.
I have also run the BE app (Spring boot) on localhost:8000 and I receive a 401 Unauthorized error when I browse it directly, as expected.
The problem comes when I am logged-in and click on "Messages" tab. I get this:
![image](https://user-images.githubusercontent.com/39133697/142929476-bcf9f47e-829b-4629-b91b-e480fa3e39dd.png)

I can share this too:
![image](https://user-images.githubusercontent.com/39133697/142929989-8f512b32-c990-44ff-93fb-927c3ba49f87.png)

The FE app is started just with "ng serve", and the BE launching command I use is:
mvn -Dokta.oauth2.issuer=https://dev-16944632.okta.com -Dokta.oauth2.client-id=0oa2ujzfybi9wW6jB5d7

Those are my real issuer&clientId.
The rest of my Okta app is like this:
![image](https://user-images.githubusercontent.com/39133697/142930833-8a3897ba-a4bd-476a-9096-26b86fb49159.png)
![image](https://user-images.githubusercontent.com/39133697/142930884-87341815-80ff-4e62-a834-382c818449c2.png)

I have  CORS enabled for localhost:8080 as I needed it for the angular app to get to work, and tried enabling also for localhost:8000 although I think I is unrelated

I have read all the readme files and also all the issues but I cannot understand why the JWT is not valid for the BE app.
I am a bit lost, could anyone try to help me solving this?
Muchas gracias,
Alvaro

**Comment by VitaliiTytarenko-okta** [comment]
Hi @alvarocamina 
I've included this issue in our roadmap. Internal ref: [OKTA-448762](https://oktainc.atlassian.net/browse/OKTA-448762)
We will investigate your case and provide you with detailed information.
Thanks for using Okta!

**Comment by alvarocamina** [comment]
Hi @VitaliiTytarenko-okta,
Thanks for getting involved in this issue.
I appreciate you even took the time to open an internal ticket in Okta, but un fortunately I cannot follow it up. 
So I have to ask, is there any advance?
Should you need further data, trace or whatever, I'll be glad to share.
Thanks again,
Álvaro Camina

**Comment by VitaliiTytarenko-okta** [comment]
@alvarocamina 
I'm working on your issue.
Reference to the ticked - just for your info.
I'll get back to you soon with more details.

**Comment by VitaliiTytarenko-okta** [comment]
Hi, @alvarocamina 
Thanks for the detailed explanation with screenshots of your issue. I was able to reproduce this and deal with it.
And to make it work you just need to **add** `/oauth2/default` to **_issuer_**. So, you should run the app with:
```
mvn -Dokta.oauth2.issuer=https://dev-16944632.okta.com/oauth2/default
```
The rest remained unchanged.

<img width="400" alt="Screenshot 2021-11-26 at 15 23 27" src="https://user-images.githubusercontent.com/74187216/143588004-7245c6e0-8889-41c3-af72-9ea4fa7f154d.png">

`samples-js-angular/custom-login` configuration (just to be on the same page):
```
export default {
  oidc: {
    clientId: `0oa2ujzfybi9wW6jB5d7`,
    issuer: `https://dev-16944632.okta.com/oauth2/default`,
    redirectUri: 'http://localhost:8080/login/callback',
    scopes: ['openid', 'profile', 'email'],
    testing: {
      disableHttpsCheck: `true`
    },
  },
  widget: {
    useInteractionCodeFlow: `false`,
  },
  resourceServer: {
    messagesUrl: 'http://localhost:8000/api/messages',
  },
};
```
Feel free to reopen this if you have any further difficulties with this case.
Take care. Thanks for using Okta!
