### ISSUE TITLE
invalid_token_response

### ISSUE THREAD

**Issue by neerazz** [okta/samples-java-spring#38]
I am getting a the below token error. I have cloned the project and have replaced the client-id and clientsecret.

Login Page is loaded with URL: https://dev-763068.oktapreview.com/login/login.htm?fromURI=/oauth2/v1/authorize/redirect?okta_key=BvQsZtJm7l_qP3s_-NGKVXn79s9JMM3OhKX6p5XZLVQ

After entering the login details the URL is: http://localhost:1001/login?error

Error message:
[invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: I/O error on POST request for "https://dev-763068.oktapreview.com/oauth2/default/v1/token": dev-763068.oktapreview.com; nested exception is java.net.UnknownHostException: dev-763068.oktapreview.com

**Comment by bdemers** [comment]
Hey @neerazz!
Sorry we missed this.  Were you able to get past this? Can you add the full stack track?

**Comment by neerazz** [comment]
@bdemers The problem was sorted out. I was giving an incorrect Login redirect URIs.

**Comment by bdemers** [comment]
Thanks for the follow up @neerazz !
