### ISSUE TITLE
Okta-hosted-login sample app "logout" button does not log out a user.

### ISSUE THREAD

**Issue by andyxtran** [okta/samples-java-spring#51]
When running the Okta-hosted-login sample app, clicking the logout button redirects me back to the home page. Issue comes when clicking the login button... it sends me back to the user's profile page instead of redirecting to okta's login page. The login doesn't actually log out a user. This is true for both normal and incognito browser mode.

**Comment by bdemers** [comment]
Thanks @andyxtran !

We are tracking this under: okta/okta-spring-boot#126
This will be supported in the next version of Spring Security.

We will have the option to kill the application's session, or both the application session and the "SSO Session".

You can try out Spring Security 5.2 M2 if you want to give it a shot today.

**Comment by andyxtran** [comment]
Ok great, thanks!

**Comment by vekdeq** [comment]
Hi Brian, How to try this using Spring Security 5.2 version. I am having Okta Login page and Okta IDP as my SSO. Current spring security version is 5.1.5 with okta spring starter kit. I will explicitly add  5.2 version, but still I need to know what changes are required in code / prop configs. Can you please guide me ?

Vivek

**Comment by bdemers** [comment]
Hi @vekdeq
This is similar to a question you asked on another issue, let’s keep the thread in one place to make it easier for other folks to follow.

**Comment by vekdeq** [comment]
Yes, My apologies !! There are too many examples / blogs by different authors - but none consolidated APIs docs / examples catering all scenarios / use cases. We have already case open with Okta Team - and awaiting response. We can continue our discussion at other issue.
