### ISSUE TITLE
local example issues

### ISSUE THREAD

**Issue by focuscoder** [okta/samples-java-spring#56]
Hello , 
      I have  downloaded java example of  resource server examples and angular example, I make sure resource server it's running on port 8000. and angular example it is running. but  resource server response status code 401 and response header show : 
WWW-Authenticate: Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: Invalid token , what should i do that make it ok ?

**Comment by bdemers** [comment]
What did you use for an issuer in both of the applications?

**Comment by arvindkrishnakumar-okta** [comment]
@focuscoder Please feel free to reopen with details, if needed.
