### ISSUE TITLE
In the Example there is an error in the running script of mvn (missing space)

### ISSUE THREAD

**Issue by timsamart** [okta/samples-java-spring#57]
```powershell
mvn -Dokta.oauth2.issuer=https://{yourOktaDomain}/oauth2/default \
    -Dokta.oauth2.clientId={clientId} \
    -Dokta.oauth2.clientSecret={clientSecret}
```

should be:
```powershell
mvn -D okta.oauth2.issuer=https://{yourOktaDomain}/oauth2/default \
    -D okta.oauth2.clientId={clientId} \
    -D okta.oauth2.clientSecret={clientSecret}
```

**Comment by bdemers** [comment]
Hey @timsamart!
Maven documentation typically refers to setting system properties as the former: https://books.sonatype.com/mvnref-book/reference/running-sect-options.html

Did it not work for you?

**Comment by timsamart** [comment]
Yes that's true, but for a beginner trying out the code by copy pasting the example does not work. This could have saved me half an hour because the error thrown is not specific.

**Comment by bdemers** [comment]
Hey @timsamart I'm sorry, but I'm still not following the `-Dkey=value` syntax is valid for Maven and Java.  If that isn't working for you can you run `mvn --version` and include the output below?

**Comment by timsamart** [comment]
@bdemers I am running the example on a windows machine through the powershell maybe that's the problem?

**Comment by bdemers** [comment]
Could be, what version of Maven and Java are you using? (`mvn --version`)
This sounds like there might need to be a lot of doc changes elsewhere on the internet, so I want to make sure I have a good test case to bring back to the Maven project

**Comment by timsamart** [comment]
@bdemers 
```powershell
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin\..
Java version: 1.8.0_211, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_211\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by timsamart** [comment]
@bdemers I guess the powershell thinks that `-Dokta` is the flag because mvn tries to resolve `.oauth2.issuer` as a plugin which fails of course.

**Comment by bdemers** [comment]
Thanks @timsamart this helps! 

I just found another ref of the same problem: https://stackoverflow.com/questions/6347985/cannot-run-maven-using-mvn-d-argument-within-microsoft-powershell-but-works
