### ISSUE TITLE
401 Error when using authorization server rather than "default"

### ISSUE THREAD

**Issue by HongliBu** [okta/samples-java-spring#61]
When using resouce-server, if the okta 'default' authorization server is switched off, and the only issuer we can use is https://domain.okta.com , the program will throw 401 error"Invalid Token", how to resolve this problem?

**Comment by bdemers** [comment]
Hi @HongliBu 
When creating a Resource Server with this library, access tokens are validated locally, and only work with Okta's "custom authorization server", by out of the box developer accounts have one named "default"

You can contact sales or support to get this feature turned on.

Alternatively, you can use Spring Security directly (without the Okta starter): https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-custom-provider-properties
Just ensure you are using the "opaque" option:
https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver
