### ISSUE TITLE
Caveats in README

### ISSUE THREAD

**Issue by haishengwu-okta** [okta/samples-java-spring#64]
## Missing actual maven command

```sh
mvn -Dokta.oauth2.issuer=https://{yourOktaDomain}/oauth2/default \
    -Dokta.oauth2.clientId={clientId} \
    -Dokta.oauth2.clientSecret={clientSecret} \
    -Dokta.oauth2.postLogoutRedirectUri={absoluteLogoutRedirectUri} 
```

- Turn out it's missing `spring-boot:run` to the end.
- one nit: omit optional parameters and may have another section to describe what are all supported parameters

## How to update application.yml

```
NOTE: Putting secrets on the command line should ONLY be done for examples, do NOT do this in production. Instead update the projects application.yml
```
How to update `application.yml`? Are we assuming developers has enough knowledge of sprint-boot?
I wonder if it makes sense to just add example (for copy/parse)? It doesn't hurt even developer know how to do not to mention some one dont know (like me) and I have to google..

Thanks!

**Comment by bdemers** [comment]
This project has a default goal of `spring-boot:run` That command _should_ work as is.  Where you following these steps while working on a different project?
(I'm not against `spring-boot:run` to the doc, just trying to understand how you were following along)

Our official guides link off to https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html to explain other configuration techniques, we could put that here too.
(I do think we need to assume some familiarity with Spring Boot though)

Environment variables might be the _safest_ default, the problem there is they are set differently on windows.  Most Spring Shops will have some preferred way of setting properties, environment variables, Spring Cloud Config, config files, etc

Thoughts?

**Comment by haishengwu-okta** [comment]
I got build error if omit `sprint-boot:run`.

```
samples-java-spring git:(master) mvn -Dokta.oauth2.issuer=https://dev-494096.okta.com/oauth2/default \
    -Dokta.oauth2.clientId=0oaqr2yu0NQi1n2FO4x6 \
    -Dokta.oauth2.clientSecret=90b7xqSLDqcuefjJl2Ge444VQpJN9YwKnD3f6BLS
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.example.okta:okta-spring-boot-oauth-code-flow-example:jar:0.0.1-SNAPSHOT
[WARNING] 'parent.relativePath' of POM com.example.okta:okta-spring-boot-oauth-code-flow-example:0.0.1-SNAPSHOT (/Users/haishengwu/Downloads/samples-java-spring/okta-hosted-login/pom.xml) points at com.okta.examples:aggregator instead of org.springframework.boot:spring-boot-starter-parent, please verify your project structure @ line 6, column 13
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Okta :: Samples :: Spring Boot :: Code Flow                        [jar]
[INFO] Okta :: Samples :: Spring Boot :: Code Flow + Custom Login Page    [jar]
[INFO] Okta :: Samples :: Spring Boot :: Front End                        [jar]
[INFO] Okta :: Samples :: Spring Boot :: Resource Server                  [jar]
[INFO] Okta Spring Samples :: Aggregator                                  [pom]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Okta :: Samples :: Spring Boot :: Code Flow 0.0.1-SNAPSHOT SKIPPED
[INFO] Okta :: Samples :: Spring Boot :: Code Flow + Custom Login Page 0.0.1-SNAPSHOT SKIPPED
[INFO] Okta :: Samples :: Spring Boot :: Front End 0.0.1-SNAPSHOT SKIPPED
[INFO] Okta :: Samples :: Spring Boot :: Resource Server 0.0.1-SNAPSHOT SKIPPED
[INFO] Okta Spring Samples :: Aggregator 1-SNAPSHOT ....... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.661 s
[INFO] Finished at: 2020-08-19T12:40:14-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
```

If I understand correctly, one nuance when converting to `yml` is `clientId` becomes `client-id`. 
I feel it's just convenient for developer to copy/parse regardless they have knowledge of sprint boot or not.
Basically I was thinking I can start the App from cli by using variable from 
- either cli as mvn parameter
- or `application.yml`

My 2cents was we can let developer spin up the App as quick as possible.
And leave note saying what might be best to use in practice (application.yml or env variable) base on my assumption that
- this is sample app which needs to give developer quick taste on **Identify** (authentication)
- they probably have their real project which already has way on how to use env variable. they may or may not take our suggestions on project set up.

**Comment by bdemers** [comment]
Ahh, I think part of the problem is you missed the `cd okta-hosted-login` in the same code block
This repo contains multiple examples in it (to match the other "samples" repos)

**Comment by haishengwu-okta** [comment]
oh... 🤦 🤦  I'm idiot!

**Comment by haishengwu-okta** [comment]
Thanks @bdemers for helping my mistake! I'll close the ticket and leave the `application.yml` whether you like to add sample config.

**Comment by bdemers** [comment]
@haishengwu-okta no, I think it's a valid point. I'm not a big fan of the multiple examples in one repo, it makes it harder to grab just that one example.

I do like the consistency between projects, but I think we could try to call this out more.
