### ISSUE TITLE
Resource Server (Java) fails with missing bean org.springframework.security.oauth2.jwt.JwtDecoder

### ISSUE THREAD

**Issue by LeslieMurphy** [okta/samples-java-spring#77]
if 

```
okta:
  oauth2:
    issuer: https://dev-xxxx.okta.com/oauth2/default
```

is not defined in application.yml (or via mvn -Dokta.oauth2.issuer=https://{yourOktaDomain}/oauth2/default)

a cryptic error message is generated.   Can you enhance to produce a better message?

This is the error that is generated:

Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' that could not be found.

**Comment by bdemers** [comment]
Thanks @LeslieMurphy which version are you using?

Do you have a WebSecurityConfigurationAdapter? if so what does it look like?

**Comment by LeslieMurphy** [comment]
I believe I have the latest version from GitHub.

 

WebSecurityConfigurationAdapter comes from inside spring boot autoconfigure – 2.3.4

 

The error is triggered by OktaOAuth2ResourceServerAutoConfig

 

I was able to fix the issue as soon as I added this to my application.yml

 

okta:
  oauth2:
    issuer: https://dev-9267515.okta.com/oauth2/default

 

 

How do I tell which WebSecurityConfigurationAdapter I am using?

 

My pom.xml has this:

 

<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.3.4.RELEASE</version>
</parent>

<groupId>com.example.okta</groupId>
<artifactId>okta-spring-boot-oauth-resource-server</artifactId>
<version>0.0.1-SNAPSHOT</version>
<packaging>jar</packaging>

<name>Okta :: Samples :: Spring Boot :: Resource Server</name>
<description>Okta OAuth 2.0 w/ Spring Boot Example - Resource Server</description>

<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <java.version>1.8</java.version>
</properties>

<dependencies>
    <dependency>
        <groupId>com.okta.spring</groupId>
        <artifactId>okta-spring-boot-starter</artifactId>
        <version>1.4.0</version>
    </dependency>

 

 

If I run without the okta config in application.yml I get this:

 

***************************

APPLICATION FAILED TO START

***************************

 

Description:

 

Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' that could not be found.

 

The following candidates were found but could not be injected:

              - Bean method 'jwtDecoder' in 'OktaOAuth2ResourceServerAutoConfig' not loaded because @ConditionalOnProperty (spring.security.oauth2.resourceserver.jwt.jwk-set-uri) did not find property 'spring.security.oauth2.resourceserver.jwt.jwk-set-uri'

              - Bean method 'jwtDecoderByIssuerUri' in 'OAuth2ResourceServerJwtConfiguration.JwtDecoderConfiguration' not loaded because OpenID Connect Issuer URI Condition did not find issuer-uri property

              - Bean method 'jwtDecoderByJwkKeySetUri' in 'OAuth2ResourceServerJwtConfiguration.JwtDecoderConfiguration' not loaded because @ConditionalOnProperty (spring.security.oauth2.resourceserver.jwt.jwk-set-uri) did not find property 'spring.security.oauth2.resourceserver.jwt.jwk-set-uri'

              - Bean method 'jwtDecoderByPublicKeyValue' in 'OAuth2ResourceServerJwtConfiguration.JwtDecoderConfiguration' not loaded because Public Key Value Condition did not find public-key-location property

 

 

Action:

 

Consider revisiting the entries above or defining a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' in your configuration.

**Comment by bdemers** [comment]
That's helpful!  If you don't have a `WebSecurityConfigurationAdapter` then the default one provided by Spring Sec is used.
You don't need to worry about it, I just wanted to make sure I was testing the same case.

We are working on another release, I'll try to reproduce that and see if we can make the error better (or probably just not fail)
i.e. in this case you don't have any security configure, so the app _should_ fallback to Spring Security's defaults

**Comment by LeslieMurphy** [comment]
Sounds good.  Throwing an exception is fine – just hopefully a better message!

 

Thanks!

**Comment by arvindkrishnakumar-okta** [comment]
@LeslieMurphy Thanks for raising this. 

I have created an internal issue to address this (OKTA-339695).

**Comment by arvindkrishnakumar-okta** [comment]
Fixed.

**Comment by woldie** [comment]
Hey @bdemers, given the way the PR for this issue went down and per the documentation at https://github.com/okta/okta-spring-boot, the application.properties you refer to at 

    https://developer.okta.com/blog/2020/03/27/spring-oidc-logout-options

probably needs to change from

```
spring.security.oauth2.client.provider.okta.issuer-uri={yourOktaDomain}/oauth2/default
spring.security.oauth2.client.registration.okta.client-id={client-id-from-above}
spring.security.oauth2.client.registration.okta.client-secret={client-secret-from-above}
```

to

```
okta.oauth2.issuer={yourOktaDomain}/oauth2/default
okta.oauth2.clientId={client-id-from-above}
okta.oauth2.clientSecret={client-secret-from-above}
```

BTW, I don't believe the PR addressed this issue at all.  I was just experimenting with the spring.security.oauth2.* properties, and I got the exact cryptic error message that OP got.  I'm bound to com.okta.spring:okta-spring-boot-starter:2.0.1 

I'm fine sticking to the okta.oauth2.* properties, but you should eradicate all traces of spring.security.oauth2.* from your blogs and docs so as not to confuse users like me.   :)

**Comment by bdemers** [comment]
Hi @woldie!

This _should_ be fixed in the next release.  We added tests (and fixes) to make sure that both the `okta.oauth2.*` and standard `spring.security.oauth2.*` properties work.
(**Note:** the `okta.oauth2` properties are just alias to the Spring props)

cc: @arvindkrishnakumar-okta

**Comment by woldie** [comment]
lovely, thank you!
