### ISSUE TITLE
Sample doesn't seem to work as advertised in the Readme

### ISSUE THREAD

**Issue by gishu** [okta/samples-java-spring#90]
I followed the instructions as documented here - https://github.com/okta/samples-java-spring/tree/master/front-end

The request to obtain a token fails with a 401 and the following response.
{“error”:“invalid_client”,“error_description”:“Client authentication failed. Either the client or the client credentials are invalid.”}

The instructions do not mention setting the client-secret anywhere. 

See also: [Okta Forum Question](https://devforum.okta.com/t/the-github-java-sample-fails-with-a-401-while-obtaining-a-token/13083)

**Comment by sergiishamrai-okta** [comment]
The front-end sample application works together with [Resourse Server](https://github.com/okta/samples-java-spring/tree/master/resource-server) sample application.

Please, make sure that you using the SPA application. Any other application-type will fail.
