### ISSUE TITLE
Please update Widget version in Login.html

### ISSUE THREAD

**Issue by MSchaffer360** [okta/samples-java-spring#97]
mraible of the Okta Team suggested that I request you to update the version number of the Login Widget in login.html to "5.5.2"  .

This appears in the "script" and "link" HTML statements to load resources from the Okta CDN.

Mr. Raible said, "Upgrading the version number in the CDN URLs shouldn’t cause any issues."

Thank you.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting! We will update it.

**Comment by arvindkrishnakumar-okta** [comment]
Upgraded widget to 5.6.4
